[[headers]]
for = "/data.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
[[headers]]
for = "/*.js"
  [headers.values]
  Content-Type = "application/javascript"
